### ISSUE TITLE
Allow per guild preferences

### ISSUE THREAD

**Issue by gris-martin** [gris-martin/teamo#1]
Per guild preferences should be stored in a database and accessed when needed. Some preferences:

- In which channel(s) can Teamo be used?
  - Type: int or null
    - int -> channel id
    - null -> everywhere
  - Default: Create "Teamo" channel and set its ID as default
- In which channel should Teamo post "Time for ..." messages?
  - Type: int or null
    - int -> channel id
    - null -> same as the channel where the command was posted
    - Default: null
- In which channel should Teamo post "Game @ xx:yy" messages?
  - Type: int or null
    - int -> channel id
    - null -> same as the channel where the "Time for ..." message was posted
  - Default: null
- Should "Game @ xx:yy" messages be deleted?
  - Type: int
    - \>= 0 -> Message should be deleted after this time
    - < 0 -> Message will never be deleted
  - Default: 15 mins

## TODO

- [x] Create default db entries for all servers that don't already have an entry
- [x] Allow changing settings using chat (only allow for admins/special role?)
- [x] Use the settings when creating messages
- [x] Command for showing all settings
